### ISSUE TITLE
"message":"The image content must be valid base64 encoded data.

### ISSUE THREAD

**Issue by matteobaro** [olivertar/m2_api_product_images#1]
Hello i have try, but your extension doesn't work, there is an update?

error: "message":"The image content must be valid base64 encoded data.

**Comment by cad-software** [comment]
I tested today with Magento ver. 2.3.5-p2. Same error here.

I had to edit 'MediaGalleryProcessorPlugin.php' and replace every occurance of
$entry['content'][ImageContentInterface::BASE64_ENCODED_DATA]
with 
$entry['content']['data'][ImageContentInterface::BASE64_ENCODED_DATA]

Now the extension works without the mentioned error 'The image content must be valid base64 encoded data.'

Hope this helps.

**Comment by olivertar** [comment]
@cad-software thanks for your contribution. The code was made for a very old version of M2.
It would be very useful for other users if you do a PR with the changes.

**Comment by cfarnleitner** [comment]
Magento v2.4.1

here for all the same reason, good catch @cad-software, two points in addition though:
1) `$mediaGalleryEntries[$k]['content'][ImageContentInterface::BASE64_ENCODED_DATA]` is to be changed to `$mediaGalleryEntries[$k]['content']['data'][ImageContentInterface::BASE64_ENCODED_DATA]` too as otherwise the final array structure is incorrect leading to the same error message
2) see PR ;)

Obviously, big thanks to @olivertar too!

**Comment by VaseemEyewa** [comment]
It worked very well as required.

**Comment by olivertar** [comment]
Fixed by @cfarnleitner
